### ISSUE TITLE
rly paths fetch issue:  runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CatBosss** [cosmos/relayer#1046]
rly paths fetch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x125ac09]

goroutine 1 [running]:
github.com/cosmos/relayer/v2/relayer.(*Chain).ChainID(...)
	/www/wwwroot/relaytest/relayer/relayer/chain.go:91
github.com/cosmos/relayer/v2/cmd.pathsFetchCmd.func1(0xc000e65180, {0x231b888?, 0x0?, 0x0?})
	/www/wwwroot/relaytest/relayer/cmd/paths.go:338 +0x6c9
github.com/spf13/cobra.(*Command).execute(0xc000e65180, {0x231b888, 0x0, 0x0})
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e60280)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/relayer/v2/cmd.Execute()
	/www/wwwroot/relaytest/relayer/cmd/root.go:175 +0x14d
main.main()
	/www/wwwroot/relaytest/relayer/main.go:6 +0x17

**Comment by CatBosss** [comment]
use v2.1.0.
