### ISSUE TITLE
Relayer does not allow to transfer tokens between 3 different chains (invalid coin set)

### ISSUE THREAD

**Issue by asmodat** [cosmos/relayer#215]
If you try to send coins from chain A to B to C the relayer fails with `invalid coin set` error

```
Call 'rly tx transfer kira-alpha stakingfund 2transfer/kwtfdddxjm/transfer/wutnqqfrcp/samoleans true cosmos13tyaljtac4l9jfen4uz338qdmklaupktgtwsrl
' failed with status 2, error: panic: invalid coin set: 2transfer/lpgmlolnzk/transfer/kwtfdddxjm/transfer/wutnqqfrcp/samoleans

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types.NewCoins(0xc000027c20, 0x1, 0x1, 0xc001087c50, 0x2d, 0xc000102c80)
        /home/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200423152229-f1fdde5d1b18/types/coin.go:155 +0x295
github.com/iqlusioninc/relayer/relayer.(*Chain).SendTransferBothSides(0xc000cc5b00, 0xc000d26360, 0xc000102c80, 0x45, 0xc000f5e6c0, 0xc00107fa80, 0x14, 0x20, 0x1, 0xc000f46cf0, ...)
        /home/go/src/github.com/iqlusioninc/relayer/relayer/packet-tx.go:104 +0x2eb
github.com/iqlusioninc/relayer/cmd.transferCmd.func1(0xc0005ba580, 0xc000c08870, 0x5, 0x5, 0x0, 0x0)
        /home/go/src/github.com/iqlusioninc/relayer/cmd/xfer.go:95 +0x467
github.com/spf13/cobra.(*Command).execute(0xc0005ba580, 0xc000c08820, 0x5, 0x5, 0xc0005ba580, 0xc000c08820)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x20c6c40, 0x44563a, 0x20568c0, 0xc000000180)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/iqlusioninc/relayer/cmd.Execute()
        /home/go/src/github.com/iqlusioninc/relayer/cmd/root.go:114 +0x55
main.main()
        /home/go/src/github.com/iqlusioninc/relayer/main.go:21 +0x20

FAILURE: Failed sending 2transfer/kwtfdddxjm/transfer/wutnqqfrcp/samoleans from kira-alpha to stakingfund
``

**Comment by jackzampolin** [comment]
I think this is due to the max denom length. cc @cwgoes

**Comment by cwgoes** [comment]
Yes, at present there is a hard limit. It can be extended, but not indefinitely.

The relevant code is at https://github.com/cosmos/cosmos-sdk/blob/master/types/coin.go#L583.

**Comment by jackzampolin** [comment]
We have fixed this in the SDK with IBC denoms.
