### ISSUE TITLE
Segmentation fault when query a newly created path

### ISSUE THREAD

**Issue by kwunyeung** [cosmos/relayer#227]
```
rly q full-path desmos-hub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef9a1f]

goroutine 1 [running]:
github.com/iqlusioninc/relayer/relayer.QueryPathStatus(0xc00029d7a0, 0xc00029d9e0, 0xc0001b4580, 0x11, 0xc00027ff70, 0x2)
	/home/ubuntu/relayer/relayer/query.go:901 +0x59f
github.com/iqlusioninc/relayer/cmd.queryFullPathCmd.func1(0xc000c26000, 0xc000288a30, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/relayer/cmd/query.go:722 +0x201
github.com/spf13/cobra.(*Command).execute(0xc000c26000, 0xc000288a10, 0x1, 0x1, 0xc000c26000, 0xc000288a10)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x201cdc0, 0x4456da, 0x1fad7c0, 0xc000000180)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/iqlusioninc/relayer/cmd.Execute()
	/home/ubuntu/relayer/cmd/root.go:114 +0x55
main.main()
	/home/ubuntu/relayer/main.go:21 +0x20
```

**Comment by jackzampolin** [comment]
This looks like a version mismatch issue. Please check your versions and try to reproduce.
