### ISSUE TITLE
panic: runtime error when using rly pth add command

### ISSUE THREAD

**Issue by asmodat** [cosmos/relayer#233]
It is currently not possible to add path from file

Steps to reproduce:

1. Initalize & save path to file
```
m="mnemonic words come here twenty four of them all" && \
 j1=./zone.json && \
 j2=./hub.json && \
 i=$(cat $j1) && s=$(echo $i | jq -r '."chain-id"') && \
 o=$(cat $j2) && d=$(echo $o | jq -r '."chain-id"') && \
 p="$s-$d" && \
 rly ch a -f $j1 && rly ch a -f $j2 && \
 rly k d $s k$s ||: && rly k d $d k$d ||: && \
 rly k r $s k$s "$m" && rly k r $d k$d "$m" && \
 rly ch e $s key k$s && rly ch e $d key k$d && \
 rly l d $s && rly l d $d && rly pth d $p ||: && \
 rly pth gen $s transfer $d transfer $p -f && \
 rly pth s $p -j > p
```

2. Re-initalize and add path from file

```
rly ch a -f $j1 && rly ch a -f $j2 && \
 rly k d $s k$s ||: && rly k d $d k$d ||: && \
 rly k r $s k$s "$m" && rly k r $d k$d "$m" && \
 rly ch e $s key k$s && rly ch e $d key k$d && \
 rly l d $s && rly l d $d && rly pth d $p ||: && \
 rly pth add $s $d $p --file ./p
```

Result:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xee6576]

goroutine 1 [running]:
github.com/iqlusioninc/relayer/relayer.(*PathEnd).Vclient(...)
        /home/go/src/github.com/iqlusioninc/relayer/relayer/ics24.go:12
github.com/iqlusioninc/relayer/relayer.(*PathEnd).Validate(0x0, 0xc0005c44b8, 0x16)
        /home/go/src/github.com/iqlusioninc/relayer/relayer/ics24.go:67 +0x26
github.com/iqlusioninc/relayer/relayer.(*Path).Validate(0xc000c12b20, 0x50a6b2, 0xc0005b5b80)
        /home/go/src/github.com/iqlusioninc/relayer/relayer/path.go:110 +0x32
github.com/iqlusioninc/relayer/relayer.Paths.Add(0xc000585770, 0x7fff81c91006, 0x11, 0xc000c12b20, 0xc0005c44b8, 0x0)
        /home/go/src/github.com/iqlusioninc/relayer/relayer/path.go:50 +0x2f
github.com/iqlusioninc/relayer/cmd.fileInputPathAdd(0x7fff81c9101f, 0x3, 0x7fff81c91006, 0x11, 0x3, 0x0, 0x0)
        /home/go/src/github.com/iqlusioninc/relayer/cmd/paths.go:607 +0x13b
github.com/iqlusioninc/relayer/cmd.pathsAddCmd.func1(0xc000454580, 0xc0005905f0, 0x3, 0x5, 0x0, 0x0)
        /home/go/src/github.com/iqlusioninc/relayer/cmd/paths.go:576 +0x1f8
github.com/spf13/cobra.(*Command).execute(0xc000454580, 0xc0005905a0, 0x5, 0x5, 0xc000454580, 0xc0005905a0)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x201ada0, 0x4455aa, 0x1fab7a0, 0xc000000180)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/iqlusioninc/relayer/cmd.Execute()
        /home/go/src/github.com/iqlusioninc/relayer/cmd/root.go:114 +0x55
main.main()
        /home/go/src/github.com/iqlusioninc/relayer/main.go:21 +0x20
```

**Comment by iammelea** [comment]
--file ~/some.config.file.yaml

No works?

**Comment by asmodat** [comment]
> --file ~/some.config.file.yaml
> 
> No works?

No it does not, the add without --file works - with manual input, however with file input - which is the most useful it fails with above error. 

I am trying to create a stateless rly so that I can run it on lambda (save path on s3 and drop the local state later) and this issue is important for me to be resolved.

**Comment by asmodat** [comment]
Also please add an option to import json directly from the console input, rather than having to type every single value manually and confirm with enter.
It can be another way how this issue can be fixed

**Comment by jackzampolin** [comment]
This is because we added the `pathStatus` to the JSON export. This was a requested feature, but it broke import. What would be best? keep the path status on the export and ignore it on the import, or only leave the path status on the string output and omit it from the JSON output?

**Comment by jackzampolin** [comment]
Need to rework all this path stuff... closing and putting up a meta issue around the needed path work.
