### ISSUE TITLE
while the rly start is running, an panic: runtime error

### ISSUE THREAD

**Issue by gruberx** [cosmos/relayer#267]
When gameofzoneshub-2a started, after 45 minutes, rly start often crashed with a panic: runtime error: invalid memory address or nil pointer dereference error.
I noticed two types of errors:
```
I[2020-05-25|07:44:19.337] • [gameofzoneshub-2a]@{20143} - actions(0:transfer) hash(9FFD1CCC6354ACEB2D9A06EE11EDF872A98AA4837BF7A3274859B70D500B8411)
I[2020-05-25|07:44:19.337] • [gameofzoneshub-2a]@{20143} - actions(0:update_client,1:ics04/opaque) hash(B6282C88C836B98725B5838A5821056EB1F4956473CFC10A66EE9D5C0CAB16F0)
I[2020-05-25|07:44:19.337] • [gameofzoneshub-2a]@{20143} - actions() hash(D4A54C3120E4297C0F373D6A9C971292B27A3395A84896FDAED51B9D5DEF669F)
I[2020-05-25|07:44:24.589] ✔ [grbx-route-2]@{4893} - msg(0:update_client,1:ics04/opaque) hash(722840A3D304D0911EFB2DC7BBBAB69FDB41224095A43595E434ABE624636281)
E[2020-05-25|07:45:11.052] grbx-route-2: err(All attempts fail:
#1: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#2: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#3: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#4: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#5: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#6: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#7: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#8: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#9: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#10: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58))
E[2020-05-25|07:45:11.052] gameofzoneshub-2a: err(All attempts fail:
#1: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#2: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#3: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#4: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#5: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#6: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#7: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#8: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#9: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58)
#10: - [grbx-route-2]@{4891} - Packet Commitment Proof is nil seq(58))
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf2bb35]

goroutine 9179 [running]:
github.com/iqlusioninc/relayer/relayer.(*RelayMsgs).Send(0xc003d9fe10, 0xc0001fb7a0, 0xc0001fb8c0)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/relayMsgs.go:56 +0xc5
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).sendTxFromEventPackets.func1(0x10cec00, 0xa)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:176 +0x39d
github.com/avast/retry-go.Do(0xc003d9ff18, 0x0, 0x0, 0x0, 0x1534d80, 0xc003a406e0)
        /home/gozubnsu/go/pkg/mod/github.com/avast/retry-go@v2.6.0+incompatible/retry.go:114 +0x15b
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).sendTxFromEventPackets(0xc000e87140, 0xc0001fb7a0, 0xc0001fb8c0, 0xc001060000, 0x1, 0x1, 0xc0003736e0)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:160 +0x157
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).HandleEvents(0xc000e87140, 0xc0001fb7a0, 0xc0001fb8c0, 0xc0003736e0, 0xc001f83470)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:47 +0x9e
created by github.com/iqlusioninc/relayer/relayer.relayerListenLoop
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/strategies.go:145 +0xc38
```

```
`[2020-05-25|07:52:17.626] • [gameofzoneshub-2a]@{20225} - actions(0:transfer) hash(0B11759E266E46A96736A46C7DD0B5078B6DF6C30F2E3CA6767B17B00E7DE8F3)
I[2020-05-25|07:52:19.905] • [grbx-route-2]@{4974} - actions(0:transfer) hash(993F748367E1B86C40D9E6BBF7F901136E3BBC9D4D9D17BAC203AB3B5FD376D6)
E[2020-05-25|07:53:09.097] gameofzoneshub-2a: err(All attempts fail:
#1: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#2: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#3: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#4: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#5: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#6: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#7: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#8: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#9: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#10: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63))
E[2020-05-25|07:53:09.097] grbx-route-2: err(All attempts fail:
#1: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#2: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#3: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#4: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#5: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#6: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#7: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#8: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#9: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63)
#10: - [gameofzoneshub-2a]@{20224} - Packet Ack Proof is nil seq(63))
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf2cd18]

goroutine 437 [running]:
github.com/iqlusioninc/relayer/relayer.(*relayMsgPacketAck).Msg(0xc001926d20, 0xc0005c78c0, 0xc0005c77a0, 0xc0005ad580, 0x0)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/relayPackets.go:171 +0xd8
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).sendTxFromEventPackets.func1(0x10cec00, 0xa)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:173 +0x302
github.com/avast/retry-go.Do(0xc0033f3f18, 0x0, 0x0, 0x0, 0x1534d80, 0xc001fa66a0)
        /home/gozubnsu/go/pkg/mod/github.com/avast/retry-go@v2.6.0+incompatible/retry.go:114 +0x15b
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).sendTxFromEventPackets(0xc000e88e60, 0xc0005c78c0, 0xc0005c77a0, 0xc0002c7c20, 0x1, 0x1, 0xc0005b0940)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:160 +0x157
github.com/iqlusioninc/relayer/relayer.(*NaiveStrategy).HandleEvents(0xc000e88e60, 0xc0005c78c0, 0xc0005c77a0, 0xc0005b0940, 0xc001cdf4d0)
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/naive-strategy.go:47 +0x9e
created by github.com/iqlusioninc/relayer/relayer.relayerListenLoop
        /home/gozubnsu/go/src/github.com/iqlusioninc/relayer/relayer/strategies.go:148 +0xb85
```

**Comment by jackzampolin** [comment]
This code has been substantially refactored. Closing this issue as non-actionable. Please reopen if you can repro with existing code.
