### ISSUE TITLE
Add argument number check to rly cfg add-dir

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#292]
```
rly cfg add-dir
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ovrclk/relayer/cmd.configAddDirCmd.func1(0xc0000ca580, 0x21a5618, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/ovrclk/relayer/cmd/config.go:153 +0xaa
github.com/spf13/cobra.(*Command).execute(0xc0000ca580, 0x21a5618, 0x0, 0x0, 0xc0000ca580, 0x21a5618)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x215cd20, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/ovrclk/relayer/cmd.Execute()
	/root/go/src/github.com/ovrclk/relayer/cmd/root.go:112 +0x4d
main.main()
	/root/go/src/github.com/ovrclk/relayer/main.go:21 +0x25
```

**Comment by jackzampolin** [comment]
Addressed in 
https://github.com/cosmos/relayer/pull/318
