### ISSUE TITLE
panic on trying to connect with "unset" keys

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#297]
```
rly tx link cosmicslippers -d -o 3s
I[2020-10-20|16:28:54.028] - [slippy-0] -> creating client (thestargate) for [stargate-4]header-height{79541} trust-period(336h0m0s) 
panic: The specified item could not be found in the keyring

goroutine 1 [running]:
github.com/ovrclk/relayer/relayer.(*Chain).MustGetAddress(...)
	/root/go/src/github.com/ovrclk/relayer/relayer/chain.go:350
github.com/ovrclk/relayer/relayer.(*Chain).CLIContext(0xc000e09500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/ovrclk/relayer/relayer/chain.go:275 +0x517
github.com/ovrclk/relayer/relayer.(*Chain).QueryUnbondingPeriod(0xc000e09500, 0xc000e09500, 0x136b5, 0x187c0e0)
	/root/go/src/github.com/ovrclk/relayer/relayer/query.go:362 +0x4c
github.com/ovrclk/relayer/relayer.(*Chain).CreateClients(0xc000e09400, 0xc000e09500, 0xc000ddbd00, 0xa)
	/root/go/src/github.com/ovrclk/relayer/relayer/client-tx.go:25 +0x5f0
github.com/ovrclk/relayer/cmd.linkCmd.func1(0xc000dfe840, 0xc000d85b40, 0x1, 0x4, 0x0, 0x0)
	/root/go/src/github.com/ovrclk/relayer/cmd/tx.go:189 +0x178
github.com/spf13/cobra.(*Command).execute(0xc000dfe840, 0xc000d85ac0, 0x4, 0x4, 0xc000dfe840, 0xc000d85ac0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x215cd20, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/ovrclk/relayer/cmd.Execute()
	/root/go/src/github.com/ovrclk/relayer/cmd/root.go:112 +0x4d
main.main()
	/root/go/src/github.com/ovrclk/relayer/main.go:21 +0x25

rly chains list
 0: slippy-0             -> key(✔) bal(✔) light(✔) path(✔)
 1: stargate-4           -> key(✘) bal(✘) light(✔) path(✔)

rly keys list stargate-4
key(0): str -> cosmos1vte0c8t2c3ksn6q3j9km775wnnp303sc64z3lg

gaiad q bank balances cosmos1vte0c8t2c3ksn6q3j9km775wnnp303sc64z3lg --chain-id stargate-4 --node http://35.223.51.79:26657
balances:
- amount: "50000000"
  denom: umuon
pagination:
  next_key: null
  total: "0"
```

I think an error could be returned in place of the panic. Also, how do I add they key? I have funds and the rly can list my key so I'm confused why it isn't connected with the chain

**Comment by jackzampolin** [comment]
@colin-axner the key that will be used by default needs to be set in the `Chain` config. Will modify this to not panic however

**Comment by jackzampolin** [comment]
Closing as addressed by defensive checks added in `cmd`
