### ISSUE TITLE
Nil pointer exception when adding a new path from a file

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#846]
On current main branch there appears to be an issue with adding paths to the config from a file.

The command: `rly paths add axelar-dojo-1 crescent-1 axelar-crescent --file axelar-crescent.json`

The output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1244fe3]

goroutine 1 [running]:
github.com/cosmos/relayer/v2/cmd.(*Config).ValidatePathEnd(0xc000f3acc0, {0x18a0b80, 0xc000e0c440}, {0x188e7a0, 0xc000010020}, 0x0)
	/home/anon/go/github.com/cosmos/relayer/cmd/config.go:585 +0x43
github.com/cosmos/relayer/v2/cmd.(*Config).ValidatePath(0xc000340c00?, {0x18a0b80, 0xc000e0c440}, {0x188e7a0, 0xc000010020}, 0xc000f3ad00)
	/home/anon/go/github.com/cosmos/relayer/cmd/config.go:574 +0x50
github.com/cosmos/relayer/v2/cmd.(*appState).AddPathFromFile(0xc000ded230, {0x18a0b80, 0xc000e0c440}, {0x188e7a0, 0xc000010020}, {0x7ffc6c1467d6, 0x14}, {0x7ffc6c1467bf, 0xf})
	/home/anon/go/github.com/cosmos/relayer/cmd/appstate.go:48 +0x145
github.com/cosmos/relayer/v2/cmd.pathsAddCmd.func1(0xc000e13680, {0xc00032e960, 0x3, 0x5?})
	/home/anon/go/github.com/cosmos/relayer/cmd/paths.go:201 +0x20a
github.com/spf13/cobra.(*Command).execute(0xc000e13680, {0xc00032e910, 0x5, 0x5})
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e04f00)
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/relayer/v2/cmd.Execute()
	/home/anon/go/github.com/cosmos/relayer/cmd/root.go:175 +0x14d
main.main()
	/home/anon/go/github.com/cosmos/relayer/main.go:6 +0x17
```

File contents: 
```
{
  "axelar-crescent": {
    "src": {
      "chain-id": "axelar-dojo-1",
      "client-id": "07-tendermint-31",
      "connection-id": "connection-17"
    },
    "dst": {
      "chain-id": "crescent-1",
      "client-id": "07-tendermint-6",
      "connection-id": "connection-4"
    },
    "src-channel-filter": {
      "rule": "",
      "channel-list": []
    }
  }
}
```

**Comment by boojamya** [comment]
I think this is because you have that extra "axelar-crescent": object at the beginning. That will be added because you include the name of the path in the command.

Does this work? vvvv

```json
{
  "src": {
    "chain-id": "axelar-dojo-1",
    "client-id": "07-tendermint-31",
    "connection-id": "connection-17"
  },
  "dst": {
    "chain-id": "crescent-1",
    "client-id": "07-tendermint-6",
    "connection-id": "connection-4"
  },
  "src-channel-filter": {
    "rule": "",
    "channel-list": []
  }
}
```

**Comment by jtieri** [comment]
Good catch Dan! That did the trick.
