### ISSUE TITLE
`rly paths fetch` resulting in SIGSEV

### ISSUE THREAD

**Issue by dylanschultzie** [cosmos/relayer#982]
```
$ rly paths fetch

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x125b7c9]

goroutine 1 [running]:
github.com/cosmos/relayer/v2/relayer.(*Chain).ChainID(...)
	/root/relayer/relayer/chain.go:91
github.com/cosmos/relayer/v2/cmd.pathsFetchCmd.func1(0xc000eb2000, {0x2326888?, 0x0?, 0x0?})
	/root/relayer/cmd/paths.go:338 +0x6c9
github.com/spf13/cobra.(*Command).execute(0xc000eb2000, {0x2326888, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e9af00)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/relayer/v2/cmd.Execute()
	/root/relayer/cmd/root.go:175 +0x14d
main.main()
	/root/relayer/main.go:6 +0x17
```

- Using stride <> osmo. https://github.com/cosmos/chain-registry/blob/master/_IBC/osmosis-stride.json

```
$ rly version
version: 2.0.0
commit: unknown
cosmos-sdk: v0.45.6
go: go1.18.5 linux/amd64
```

**Comment by boojamya** [comment]
Thank your for this issue. 
The chain-registry recently changed the IBCdata struct. 

This should be fixed via: https://github.com/cosmos/relayer/pull/981
